name: CI Pipeline - Angular

on:
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Job

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci --prefix exampleCICD

      - name: Build Angular App
        run: npm run build --prefix exampleCICD -- --configuration production

      - name: Debug dist output
        run: ls -R exampleCICD/dist

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: exampleCICD/dist/exampleCICD
